name: Scala CI

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Run tests
      working-directory: data-generation
    
      run: sbt test
